global:
  domain: argocd.dev.audioprothese.ovh

certificate:
  enabled: true

server:
  autoscaling:
    enabled: true
    minReplicas: 2
  ingress:
    enabled: true
    ingressClassName: webapprouting.kubernetes.azure.com
    annotations:
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    tls: true

redis-ha:
  enabled: true

controller:
  replicas: 1

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicas: 2
