global:
  domain: argocd.dev.audioprothese.ovh

certificate:
  enabled: true

server:
  autoscaling:
    enabled: false
  ingress:
    enabled: true
    ingressClassName: webapprouting.kubernetes.azure.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      appgw.ingress.kubernetes.io/backend-protocol: "https"
      nginx.ingress.kubernetes.io/auth-url: "https://oauth2.dev.audioprothese.ovh/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://oauth2.dev.audioprothese.ovh/oauth2/start?rd=$scheme://$host$escaped_request_uri"
    tls: true

redis-ha:
  enabled: false

controller:
  replicas: 1

repoServer:
  autoscaling:
    enabled: false

applicationSet:
  replicas: 1

configs:
  params:
    server.insecure: true
    server.disable.auth: true
