---
prometheus:
  ingress:
    enabled: true
    ingressClassName: "webapprouting.kubernetes.azure.com"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    labels: {}
    path: /
    pathType: Prefix
    hosts:
      - prometheus.dev.audioprothese.ovh
    extraPaths: []
    tls:
      - hosts:
          - prometheus.dev.audioprothese.ovh
        secretName: prometheus-tls

grafana:
  adminUser: admin
  adminPassword: password
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    labels: {}
    path: /
    pathType: Prefix
    hosts:
      - grafana.dev.audioprothese.ovh
    extraPaths: []
    tls:
      - hosts:
          - grafana.dev.audioprothese.ovh
        secretName: grafana-tls
    ingressClassName: "webapprouting.kubernetes.azure.com"
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          url: http://loki-gateway.loki.svc.cluster.local/
