prometheus:
  ingress:
    enabled: true
    ingressClassName: webapprouting.kubernetes.azure.com
    hosts:
      - prometheus.dev.audioprothese.ovh
    path: /
    pathType: Prefix
    tls:
      - hosts:
          - prometheus.dev.audioprothese.ovh
        secretName: prometheus-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/auth-url: "https://oauth2.dev.audioprothese.ovh/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://oauth2.dev.audioprothese.ovh/oauth2/start?rd=$scheme://$host$escaped_request_uri"

grafana:
  adminUser: admin
  adminPassword: password
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    labels: {}
    path: /
    pathType: Prefix
    hosts:
      - grafana.dev.audioprothese.ovh
    extraPaths: []
    tls:
      - hosts:
          - grafana.dev.audioprothese.ovh
        secretName: grafana-tls
    ingressClassName: "webapprouting.kubernetes.azure.com"
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          url: http://loki-gateway.loki.svc.cluster.local/

  envFromSecret: grafana-azuread-secret

  grafana.ini:
    server:
      root_url: "https://grafana.dev.audioprothese.ovh/"
      domain: "grafana.dev.audioprothese.ovh"

    auth:
      disable_login_form: true
    
    users:
      auto_assign_org: true
      auto_assign_org_role: Admin

    auth.generic_oauth:
      enabled: true
      name: AzureAD
      client_id: $__env{GF_AUTH_GENERIC_OAUTH_CLIENT_ID}
      client_secret: $__env{GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}
      scopes: "openid profile email offline_access"
      allow_assign_grafana_admin: "true"
      auto_login: "true"
      auth_url:  "https://login.microsoftonline.com/8a25df97-9f2b-4ef1-a9e7-3faf585640e8/oauth2/v2.0/authorize"
      token_url: "https://login.microsoftonline.com/8a25df97-9f2b-4ef1-a9e7-3faf585640e8/oauth2/v2.0/token"
      api_url: "https://graph.microsoft.com/v1.0/me"
      email_attribute_path: preferred_username
      allow_sign_up: true
      log_auth_info: true
      role_attribute_path: "Admin" 
