---
prometheus:
  ingress:
    enabled: true
    ingressClassName: webapprouting.kubernetes.azure.com
    hosts:
      - prometheus.dev.audioprothese.ovh
    path: /
    pathType: Prefix

grafana:
  adminUser: admin
  adminPassword: password
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    labels: {}
    path: /
    pathType: Prefix
    hosts:
      - grafana.dev.audioprothese.ovh
    extraPaths: []
    tls:
      - hosts:
          - grafana.dev.audioprothese.ovh
        secretName: grafana-tls
    ingressClassName: "webapprouting.kubernetes.azure.com"
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          url: http://loki-gateway.loki.svc.cluster.local/

  envFromSecret: grafana-azuread-secret

  grafana.ini:
    server:
      root_url: "https://grafana.dev.audioprothese.ovh/"
      domain: "grafana.dev.audioprothese.ovh"

    auth:
      disable_login_form: true

    users:
      auto_assign_org: true
      auto_assign_org_role: Admin

    auth.generic_oauth:
      enabled: true
      name: AzureAD
      client_id: $__env{GF_AUTH_GENERIC_OAUTH_CLIENT_ID}
      client_secret: $__env{GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}
      scopes: "openid profile email offline_access"
      allow_assign_grafana_admin: "true"
      auto_login: "true"
      auth_url: "https://login.microsoftonline.com/8a25df97-9f2b-4ef1-a9e7-3faf585640e8/oauth2/v2.0/authorize"
      token_url: "https://login.microsoftonline.com/8a25df97-9f2b-4ef1-a9e7-3faf585640e8/oauth2/v2.0/token"
      api_url: "https://graph.microsoft.com/v1.0/me"
      email_attribute_path: preferred_username
      allow_sign_up: true
      log_auth_info: true
      role_attribute_path: "Admin"

alertmanager:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: webapprouting.kubernetes.azure.com
    hosts:
      - alertmanager.dev.audioprothese.ovh
    path: /
    pathType: Prefix
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ["alertname", "job", "namespace"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: telegram
      routes:
        - receiver: telegram
          matchers:
            - severity="critical"
    receivers:
      - name: telegram
        telegramConfigs:
          - botToken:
              name: telegram-bot-token-secret
              key: bot-token
            chatID: 7865397347
            parseMode: "MarkdownV2"
            disableNotifications: false
            sendResolved: true
  # templateFiles:
  #   telegram.tmpl: |-
  #     {{ define "telegram.default.message" }}
  #     {{- if eq .Status "firing" -}}
  #         {{- if eq .CommonLabels.severity "critical" -}}
  #             🔴 Alert: {{ .CommonLabels.alertname }}
  #         {{- else if eq .CommonLabels.severity "warning" -}}
  #             🟠 Alert: {{ .CommonLabels.alertname }}
  #         {{- else -}}
  #             ⚪️ Alert: {{ .CommonLabels.alertname }}
  #         {{- end }}
  #     Status: 🔥 FIRING
  #     Severity: {{ if eq .CommonLabels.severity "critical" }}🔴 {{ .CommonLabels.severity | title }}{{ else if eq .CommonLabels.severity "warning" }}🟠 {{ .CommonLabels.severity | title }}{{ else }}⚪️ {{ .CommonLabels.severity | title }}{{ end }}
  #     {{- else if eq .Status "resolved" -}}
  #         ⚪️ Alert: {{ .CommonLabels.alertname }}
  #     Status: ✅ RESOLVED
  #     Severity: {{ if eq .CommonLabels.severity "critical" }}🟢 {{ .CommonLabels.severity | title }}{{ else if eq .CommonLabels.severity "warning" }}🟢 {{ .CommonLabels.severity | title }}{{ else }}⚪️ {{ .CommonLabels.severity | title }}{{ end }}
  #     {{- end }}

  #     {{- range .Alerts -}}

  #     {{- if .Labels.job }}
  #     Job: `{{ .Labels.job }}`
  #     {{- end }}

  #     {{- if .Labels.namespace }}
  #     Namespace: `{{ .Labels.namespace }}`
  #     {{- end }}

  #     {{- if .Labels.instance }}
  #     Instance: `{{ .Labels.instance }}`
  #     {{- end }}

  #     {{- if .Annotations.runbook_url }}
  #     [RunbookURL]({{ .Annotations.runbook_url }})

  #     {{- end }}
  #     {{- end }}
  #     {{ end }}
  # alertmanagerSpec:
  #   alertmanagerConfigSelector:
  #     matchLabels:
  #       alertmanagerConfig: alertmanager-telegram
  #   alertmanagerConfigMatcherStrategy:
  #     type: None
