ingress:
  enabled: true
  annotations: {}
  labels: {}
  path: /
  pathType: Prefix
  hosts:
    - grafana.audioprothese.fchevalier.net
  extraPaths: []
  tls: []
  ingressClassName: "webapprouting.kubernetes.azure.com"
