---
ingress:
  enabled: true
  annotations: {}
  labels: {}
  path: /
  pathType: Prefix
  hosts:
    - grafana.audioprothese.duckdns.org
  extraPaths: []
  tls: []
  ingressClassName: "webapprouting.kubernetes.azure.com"

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    kubernetes-cluster-overview:
      gnetId: 12202
      revision: 1
      datasource: Prometheus
    prometheus-overview:
      gnetId: 3662
      revision: 2
      datasource: Prometheus
