name: Create Terraform plan (DEV)

on:
  pull_request:
    paths:
      - 'terraform/dev/**'
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
    inputs:
      environment:
        description: "Set the environment to deploy"
        required: true
        default: "dev"
        type: string
      iac_path:
        description: "Set the relative path of the IaC configuration"
        required: false
        default: "terraform/"
        type: string

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  plan:
    uses: ./.github/workflows/terraform-plan.yml
    with:
      environment: dev
    secrets: inherit