name: Apply Terraform plan

on:
  workflow_call:
    inputs:
      environment:
        description: "The environment to destroy (dev, prod)"
        required: true
        type: string

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      OVH_ENDPOINT: ${{ secrets.OVH_ENDPOINT }}
      OVH_CLIENT_ID: ${{ secrets.OVH_CLIENT_ID }}
      OVH_CLIENT_SECRET: ${{ secrets.OVH_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure Azure Credentials
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Apply plan
        if: ${{ github.event_name == 'push' }}
        uses: dflook/terraform-apply@v1.48.0
        with:
          path: terraform/${{ inputs.environment }}/
