name: Create Terraform plan

on:
  workflow_call:
    inputs:
      environment:
        description: "The environment to destroy (dev, prod)"
        required: true
        type: string
      iac_path:
        description: "Set the relative path of the IaC configuration"
        required: false
        default: "terraform/"
        type: string

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: terraform-fmt-check
        uses: dflook/terraform-fmt-check@v1.48.0
        with:
          path: ${{ inputs.iac_path }}${{ inputs.environment }}

  plan:
    name: Plan
    needs:
      - lint
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Azure Credentials
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Plan Terraform
        uses: dflook/terraform-plan@v1.48.0
        with:
          path: ${{ inputs.iac_path }}${{ inputs.environment }}/
